//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkEcho.Core.Test.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkEcho.Core.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Boolean&quot;: true,
        ///  &quot;Int&quot;: 123,
        ///  &quot;Double&quot;: 123.45,
        ///  &quot;String&quot;: &quot;tEsTStRing&quot;,
        ///  &quot;Guid&quot;: &quot;936da01f-9abd-4d9d-80c7-02af85c822a8&quot;,
        ///  &quot;DateTime&quot;: &quot;2030-12-12T12:23:45&quot;,
        ///  &quot;ListInt&quot;: [
        ///    987,
        ///    678
        ///  ],
        ///  &quot;ArrayInt&quot;: [
        ///    422,
        ///    324
        ///  ],
        ///  &quot;ListClass&quot;: [
        ///    {
        ///      &quot;Int&quot;: 350
        ///    },
        ///    {
        ///      &quot;Int&quot;: 260
        ///    }
        ///  ],
        ///  &quot;ArrayClass&quot;: [
        ///    {
        ///      &quot;Int&quot;: 350
        ///    },
        ///    {
        ///      &quot;Int&quot;: 260
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string TestClass_txt
        {
            get
            {
                return ResourceManager.GetString("TestClass.txt", resourceCulture);
            }
        }
    }
}
