#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ArkEcho.App.Resource", IsApplication=true)]

namespace ArkEcho.App
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LibVLCSharp.Resource.String.app_name = global::ArkEcho.App.Resource.String.app_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int cActionBarBackground = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int cActionBarTextColor = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int cMainBackground = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int cMainTextColor = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int arkecho_logo_small_blue = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int arkecho_logo_small_dark = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int arkecho_logo_small_light = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int arkecho_logo_whole_blue = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int arkecho_logo_whole_dark = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int arkecho_logo_whole_light = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int backIcon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int clearIcon = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int defaultMusicIcon = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int forwardIcon = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int menuIcon = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int playPauseIcon = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int rewindIcon = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int shuffleIcon = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int stopIcon = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int ButtonLayout = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int imageView1 = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int imageViewCoverArt = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int pbActionBarBack = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int pbActionBarMenu = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int pbBackward = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int pbConnectManually = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int pbConnectWithQr = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int pbForward = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int pbPlay_Pause = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int space1 = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int space2 = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int space3 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int space4 = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int syncMusicButton = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int teAddress = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int top_menu_help = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int top_menu_impressum = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int top_menu_syncmusicfiles = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int tvAddress = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int tvHeader = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int tvHilfe = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int tvInterpretPlayer = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int tvTitlePlayer = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int twActionBarTitle = 2130903064;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int ActionBar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Connect = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Help = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int Impressum = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int Player = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Splash = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int SyncMusicFiles = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int top_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ApplicationTitle = 2131099649;
			
			// aapt resource value: 0x7F06001E
			public const int app_name = 2131099678;
			
			// aapt resource value: 0x7F060002
			public const int HelpActivityHeader = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int HelpActivityTitle = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int ImpressumActivityHeader = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int ImpressumActivityTitle = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int MainActivityPushButtonConnectManual = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int MainActivityPushButtonConnectQr = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int MainActivityTextViewAddress = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int MainActivityTextViewHeader = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int MainActivityTitle = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int MsgBoxTextConnectionEnded = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int MsgBoxTitleError = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int PlayerActivityButtonBackward = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int PlayerActivityButtonForward = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int PlayerActivityButtonPlay_Pause = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int PlayerActivityTextViewInterpretDefault = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int PlayerActivityTextViewTitleDefault = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int PlayerActivityTitle = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int QrScannerTextBottom = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int QrScannerTextTop = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int SyncMusicFilesActivityHeader = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int SyncMusicFilesActivityLog = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int SyncMusicFilesActivitySyncButton = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int SyncMusicFilesActivityTitle = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int ToastEmptyWrongAddress = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int ToastNoConnection = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int ToastQrScanFailed = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int TopMenuHelp = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int TopMenuImpressum = 2131099677;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int ArkEcho_ActionBar = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ArkEcho_Main = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ArkEcho_SplashScreen = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
