
name: Build & Test on push

on:
  push:
    branches: 
      - master
      - develop
      - release/*

  workflow_dispatch:
  
jobs:
  build:

    #strategy:
      #matrix:
        #configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: ArkEcho.Server.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
