
name: Build & Test on push to develop

on:
  push:
    branches:
      - develop

  workflow_dispatch:
  
jobs:

  restore-build-test-server:

    runs-on: windows-latest
    
    env:
      ServerSLN: Arkecho.Server.sln
     
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Workloads
        run: dotnet workload restore
      - name: Restore Server
        run: dotnet restore ${{ env.ServerSLN }}
      - name: Build Server
        run: dotnet build ${{ env.ServerSLN }} --no-restore --configuration Release
      - name: Test
        run: dotnet test ${{ env.ServerSLN }} --no-restore
        
        
  restore-build-maui:

    runs-on: windows-latest
    
    env:
      MauiSLN: Arkecho.Maui.sln
     
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Workloads
        run: dotnet workload restore
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
         distribution: 'microsoft'
         java-version: '17'
      - name: Restore Maui
        run: dotnet restore ${{ env.MauiSLN }}
      - name: Build Maui
        run: dotnet build ${{ env.MauiSLN }} --no-restore --configuration Release -p:PublishReadyToRun=false -p:PublishTrimmed=false -p:RunAOTCompilation=false