
name: Build & Test on push

on:
  push:
    branches: 
      - master
      - develop
      - release/*

  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest
    
    env:
      ServerSLN: Arkecho.Server.sln
     
    steps:
      - uses: actions/checkout@v3
      
      #- name: Install dependencies
        #run: dotnet restore Arkecho.Server.sln
      #- name: Build
        #run: dotnet build Arkecho.Server.sln --configuration Release
      - name: Test
        run: dotnet test ArkEcho.Server.Test/ArkEcho.Server.Test.csproj
