
name: Build & Test on push

on:
  push:
    branches: 
      - master
      - develop
      - release/*

  workflow_dispatch:
  
jobs:
  restore-build-test:

    runs-on: windows-latest
    
    env:
      ServerSLN: Arkecho.Server.sln
     
    steps:
      - uses: actions/checkout@v3
      
      - name: Restore
        run: dotnet restore Arkecho.Server.sln
      - name: Build
        run: dotnet build Arkecho.Server.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test ArkEcho.Server.sln --no-restore
